### ISSUE TITLE
Add support for creating dependencies between deployments

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#132]
For example the apps project needs to depend on the network project

**Comment by umairidris** [comment]
It seems we cannot avoid using direct file paths. The simplest way I can think of to support this is to add fields like:

```
    PROJECT_TERRAFORM:
      DEPS:
      - NAME: "networks"
        PATH: "../project.example-prod-networks/networks"
```

In the project recipe.

Thus, I don't think we need output refs anymore and instead should use output paths and make it as easy to use them as possible.
