### ISSUE TITLE
Support recursive template definitions

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#136]
This is to help reduce duplication in output paths.

e.g.

```
# Top level resources
- output_path: "./live"
   templates:
   ... all these templates will be under ./live ...
   - recipe_path: "../folder"
     data:
        "PROD"
   - output_path: "./folder.prod"
     templates:
      ... all these templates will be in the prod folder ...
      
```
